# Generated by Django 4.1.2 on 2023-04-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEAFIT',
            fields=[
                ('idAdminEAFIT', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuentaAdmin', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPARKIFY',
            fields=[
                ('idAdminPARKIFY', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuentaAdmin', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('organizador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portero',
            fields=[
                ('idPortero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('usuarioEmpresaVig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('tipoVehiculo', models.CharField(max_length=10)),
                ('combustible', models.CharField(max_length=10)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.usuario')),
            ],
        ),
    ]
